export const userData = [
        {
          id: 1,
          name: 'Alice Johnson',
          gender: 'female',
          balance: 2300.75,
          birthdate: '1990-04-15T00:00:00',
          email: 'alice.johnson@example.com',
          status: 'active',
          score: 8.856,
          profileImage: 'https://xsgames.co/randomusers/assets/avatars/female/1.jpg',
          joiningDate: 1625164800000,
        },
        {
          id: 2,
          name: 'Bob Smith',
          gender: 'male',
          balance: 10500.45,
          birthdate: '1985-12-10T00:00:00',
          email: 'bob.smith@example.com',
          status: 'inactive',
          score: 9.4235,
          profileImage: 'https://xsgames.co/randomusers/assets/avatars/male/2.jpg',
          joiningDate: 1609459200000,
        },
        {
          id: 3,
          name: 'Charlie Davis',
          gender: 'male',
          balance: 560.0,
          birthdate: '1995-06-22T00:00:00',
          email: 'charlie.davis@example.com',
          status: 'active',
          score: 7.15,
          profileImage: 'https://xsgames.co/randomusers/assets/avatars/male/3.jpg',
          joiningDate: 1640995200000,
        },
        {
          id: 4,
          name: 'Diana Roberts',
          gender: 'female',
          balance: 8790.0,
          birthdate: '1992-08-19T00:00:00',
          email: 'diana.roberts@example.com',
          status: 'active',
          score: 8.65,
          profileImage: 'https://xsgames.co/randomusers/assets/avatars/female/2.jpg',
          joiningDate: 1596240000000,
        },
        {
          id: 5,
          name: 'Edward Thomas',
          gender: 'male',
          balance: 430.0,
          birthdate: '1988-03-11T00:00:00',
          email: 'edward.thomas@example.com',
          status: 'inactive',
          score: 6.45,
          profileImage: 'https://xsgames.co/randomusers/assets/avatars/male/4.jpg',
          joiningDate: 1564704000000,
        },
        {
          id: 6,
          name: 'Fiona Harris',
          gender: 'female',
          balance: 1250.0,
          birthdate: '1991-10-25T00:00:00',
          email: 'fiona.harris@example.com',
          status: 'active',
          score: 8.0,
          profileImage: 'https://xsgames.co/randomusers/assets/avatars/female/3.jpg',
          joiningDate: 1583020800000,
        },
        {
          id: 7,
          name: 'George Adams',
          gender: 'male',
          balance: 7600.0,
          birthdate: '1987-09-30T00:00:00',
          email: 'george.adams@example.com',
          status: 'active',
          score: 9.2,
          profileImage: 'https://xsgames.co/randomusers/assets/avatars/male/5.jpg',
          joiningDate: 1601510400000,
        },
        {
          id: 8,
          name: 'Hannah Collins',
          gender: 'female',
          balance: 3400.55,
          birthdate: '1993-11-17T00:00:00',
          email: 'hannah.collins@example.com',
          status: 'inactive',
          score: 7.85,
          profileImage: 'https://xsgames.co/randomusers/assets/avatars/female/4.jpg',
          joiningDate: 1612137600000,
        },
        {
          id: 9,
          name: 'Ian Miller',
          gender: 'male',
          balance: 2500.0,
          birthdate: '1986-06-21T00:00:00',
          email: 'ian.miller@example.com',
          status: 'active',
          score: 8.35,
          profileImage: 'https://xsgames.co/randomusers/assets/avatars/male/6.jpg',
          joiningDate: 1593475200000,
        },
        {
          id: 10,
          name: 'Jessica Brown',
          gender: 'female',
          balance: 950.0,
          birthdate: '1994-01-15T00:00:00',
          email: 'jessica.brown@example.com',
          status: 'active',
          score: 6.95,
          profileImage: 'https://xsgames.co/randomusers/assets/avatars/female/5.jpg',
          joiningDate: 1577836800000,
        }    
];